p8105_hw2_yy3439
================
Yuxin Yin
2023-10-03

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)
```

## Problem 1

Firstly, import the `pols-month.csv` file

``` r
pols_data = read_csv(file = "./fivethirtyeight_datasets/pols-month.csv") #import the pols-month csv file
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

#### pols_data

``` r
pols = pols_data |>
   janitor::clean_names() |> #clean-up names to r suitable names
   separate(mon, into = c("year", "month", "day"), sep = "-") |> #separate the mon variable by "-"
   mutate(
     month = as.numeric(month), #change the char variable month to numeric
     year = as.numeric(year),
     month = month.name[month]) |> #translate numeric month number to full month names
  select(-prez_dem, -prez_gop) |> #remove the prez_dem and prez_gop variables
   pivot_longer(
    gov_gop:rep_dem, #select the remaining columns
     values_to = "president") |> #and assign the values of these variables to a new variable "president"
      select(-day) #remove the day variable
```

#### snp_data

``` r
snp_data = read_csv(file = "./fivethirtyeight_datasets/snp.csv") #load the snp.csv file
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp = snp_data|>
   janitor::clean_names() |> #clean-up names to r suitable names
  mutate(date = format(as.Date(date, format = "%m/%d/%y"), "%Y/%m/%d"))|>
   separate(date, into = c("year", "month", "day"), sep = "/") |>#separate the date variable into year, month, and day
   mutate(
     year = as.numeric(year),    #change the char variable month to numeric
     year = ifelse(year >2023, year - 100, year),
     month = as.numeric(month),
      month = month.name[month]
    )|>
  select(-day)|>
  arrange(year, month)|>  #rearrange by the order of year and month
  relocate(year, month, everything())
```

#### unemploy_data

``` r
unemploy_data = read_csv(file = "./fivethirtyeight_datasets/unemployment.csv") #load the snp.csv file
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment = unemploy_data|>
   janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment"
  )|>
  mutate(
    year = as.numeric(year),
    month = month.name[match(month, tolower(month.abb))]
  )
```

#### Merging Datasets

``` r
merged_data = left_join(pols, snp, by = c("year", "month")) |>
  left_join(unemployment, by = c("year", "month"))
merged_data
```

    ## # A tibble: 4,932 × 6
    ##     year month    name    president close unemployment
    ##    <dbl> <chr>    <chr>       <dbl> <dbl>        <dbl>
    ##  1  1947 January  gov_gop        23    NA           NA
    ##  2  1947 January  sen_gop        51    NA           NA
    ##  3  1947 January  rep_gop       253    NA           NA
    ##  4  1947 January  gov_dem        23    NA           NA
    ##  5  1947 January  sen_dem        45    NA           NA
    ##  6  1947 January  rep_dem       198    NA           NA
    ##  7  1947 February gov_gop        23    NA           NA
    ##  8  1947 February sen_gop        51    NA           NA
    ##  9  1947 February rep_gop       253    NA           NA
    ## 10  1947 February gov_dem        23    NA           NA
    ## # ℹ 4,922 more rows

The `pols` dataset has 4932 observations after cleaning. This dataset
contains data related to president information and party affiliation. In
addition, the `snp` dataset has 787 observations after cleaning, and the
`unemployment` dataset has 816 observations after cleaning. The `snp`
dataset contains data related to `close` and the `unemployment` dataset
contains information related to unemployed rate. The combined dataset
has 4932 observations and 6 variables after cleaning. Finally, we
noticed that parts of both `close` and `unemployment` are missing for
the final merged dataset. We can’t simply omit all the NAs because some
appear in `close` while the others appear in `unemployment`.

## Problem 2

``` r
library(readxl)
mr_tw_data = read_excel("./fivethirtyeight_datasets/ts.xlsx", sheet = "Mr. Trash Wheel", skip = 1) #load the excel file with Mr. Trash Wheel sheet and omit the first column with figure 
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

#### Tidy Data

``` r
mr_trash_wheel_data = mr_tw_data |> 
  janitor::clean_names() |> #clean names to appropriate r format
  select(dumpster:homes_powered)|> #omit non-data entries 
  drop_na(dumpster) |> #omit rows with no dumpster-specific data 
  mutate(
    homes_powered = ((weight_tons*500)/30), #add another variable based on the calculation in the notes
    tw_name = "Mr. Trash Wheel", #to keep track of the records after combining datasets 
    year = as.numeric(year) #change the variable type to merge datasets
    
  )
```

Similarly, we follow the same cleanning process to organize the data for
Professor Trash Wheel and Gwynnda

``` r
professor_tw_data = read_excel("./fivethirtyeight_datasets/ts.xlsx", sheet = "Professor Trash Wheel", skip = 1)|>
   janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    homes_powered = ((weight_tons*500)/30),
    tw_name = "Professor Trash Wheel"

  )

gwynnda_tw_data = read_excel("./fivethirtyeight_datasets/ts.xlsx", sheet = "Gwynnda Trash Wheel", skip = 1)|>
   janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    homes_powered = ((weight_tons*500)/30),
     tw_name = "Gwynnda Trash Wheel"
  )
```

#### Combine Datasets

Finally, combining the above three datasets

``` r
trash_wheel = bind_rows(mr_trash_wheel_data, professor_tw_data, gwynnda_tw_data) |>
  select(trash_wheel_name = "tw_name", everything())
```

#### Discussion

The `Mr Trash Wheel` sheet has 584 observations. The
`Professor Trash Wheel` sheet has 106 observations, and the
`Gwynnda Trash Wheel` sheet has 155 observations. Specifically, all
these data is calculated after we omit rows with no specific dumpster
data. In addition, the final combined dataset `trash_wheel` contains 845
observations and 15 columns. Each sheet contains similar key variables
specifying various types of dumpsters: plastic bottles, polystyrene,
cigarette_butts and so on. Additionally, there are also variables such
as `weight_tons` and `volume_cubic_yards`, which can be used to quantify
the total dumpsters collected. The total weight of trash collected by
Professor Trash Wheel is 216.26, and the total number of cigarette butts
collected by Gwynnda in July of 2021 is 16300.

## Problem 3

#### Tidy up Demographic Data

``` r
mci_demographic_data = read_csv(file = "./data_mci/MCI_Baseline.csv", skip =1)|> #load the demographic csv file
  janitor::clean_names()
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline_data = mci_demographic_data|>
  janitor::clean_names()|> #recode names to appropriate r style 
  mutate(
    sex = case_match( #this part comes from class note
      sex,
      1 ~ "male",
      0 ~ "female"
    ),
    apoe4 = case_match( #follow the same logic as translating binary numeric values to categorical 
      apoe4,
      1 ~ "carrier",
      0 ~ "non-carrier"
    )
  )|>
  filter(age_at_onset !=".") #remove participants with no MCI at baseline
```

#### Discussion

Notably, we translate two numeric binary variable `sex` and `apoe4` to
categorical variables:female/male and carrier/non-carrier. In addition,
we remove participants whose `age_at_onset` is missing by using the
`filter` function. 483 participants were recruited, and 97 participants
developed MCI. The average baseline age is 65.6113402. The proportion of
women who are APOE4 carriers is approximately NA round to the nearest
integer.

#### Tidy up Longitudinally Observed Biomarker Values

``` r
mci_longitude_data = read_csv(file = "./data_mci/mci_amyloid.csv", skip =1)|> #load the demographic csv file
  janitor::clean_names()|>
  rename(id = study_id)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
amyloid = mci_longitude_data|>
  pivot_longer(
    baseline:time_8,
    names_to = "visit_time_elapsed",
    values_to = "amyloid_β_ratio"
  )|>
  drop_na(amyloid_β_ratio)
```

Similarly, import the csv file and skip line 1 because the first column
was the note. Then, rename the variable names to appropriate r style.
Also, `study_id` is renamed to `id` in order to merge the two datasets.
Additionally, n.a values are omitted after pivoting the data frame
longer.

Before merging the datasets, we can check participants that only appear
in either the baseline or amyloid dataset. We can see that 12
participants appear only in `amyloid` dataset and 8 participants only
appear in `baseline` dataset.

``` r
unique_in_amyloid  = anti_join(mci_longitude_data, mci_demographic_data, by = "id")
unique_in_amyloid
```

    ## # A tibble: 12 × 6
    ##       id baseline    time_2      time_4      time_6      time_8     
    ##    <dbl> <chr>       <chr>       <chr>       <chr>       <chr>      
    ##  1   484 0.11139422  0.110936838 0.109182887 0.110607585 0.107057538
    ##  2   485 0.106042813 0.105158363 0.107758828 0.107281321 0.106181816
    ##  3   486 0.109161071 0.114634379 <NA>        0.110035156 0.107234758
    ##  4   487 0.110821971 0.107791347 0.109855229 0.110951271 0.105861634
    ##  5   488 0.110418756 0.111994328 0.113132987 0.108902038 0.109449907
    ##  6   489 0.11477384  0.113322128 0.115109381 0.116004489 0.112260161
    ##  7   490 0.111762756 0.109627815 0.111492905 0.110104053 <NA>       
    ##  8   491 0.116934974 0.113763228 0.111358448 0.110509854 0.110541984
    ##  9   492 0.109757685 0.109912273 0.110672861 0.109064952 0.109161341
    ## 10   493 0.108357146 0.108161281 0.109491179 0.104448142 0.108636703
    ## 11   494 0.116669151 0.109711076 0.112133216 0.111399722 0.108836759
    ## 12   495 Na          0.105142354 0.108149625 0.105918659 0.102512562

``` r
unique_in_baseline  = anti_join(mci_demographic_data, mci_longitude_data, by = "id")
unique_in_baseline
```

    ## # A tibble: 8 × 6
    ##      id current_age   sex education apoe4 age_at_onset
    ##   <dbl>       <dbl> <dbl>     <dbl> <dbl> <chr>       
    ## 1    14        58.4     0        20     0 66.2        
    ## 2    49        64.7     1        16     0 68.4        
    ## 3    92        68.6     0        20     0 .           
    ## 4   179        68.1     1        16     0 .           
    ## 5   268        61.4     0        18     1 67.5        
    ## 6   304        63.8     0        16     0 .           
    ## 7   389        59.3     0        16     0 .           
    ## 8   412        67       1        16     1 .

#### Merging Datasets

``` r
full_dataset = inner_join(baseline_data, amyloid, by = c("id"))
```

There are 437 participants and 8 columns in the final merged dataset.
The average education level is 16.4851259.

#### Exporting

``` r
write.csv(full_dataset, "./data_mci/mci_full.csv")
```
